#!/bin/bash

# Set our shell to use emacs key bindings
set -o emacs

### Aliases!
alias ll="ls -al"
alias ls="ls -F"
alias rm="rm -i"

alias gs='git status'
alias gb='git branch'
alias gp='git pull --rebase'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log --stat'
alias gf='git fetch'
alias gg='git log --graph --decorate'
alias ggo='git log --graph --decorate --oneline'

### Path!
export PATH=/usr/local/apache2/bin:/usr/local/mysql/bin:$PATH
export PATH=/Applications/eclipse:$PATH
export PATH=.:~/bin:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/ruby/1.8.7-p249/bin:$PATH

# Java!
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
export CATALINA_HOME=/Library/Tomcat/Home 

# Editor!
#export EDITOR="mvim -f"
export EDITOR="subl -w"

### Terminal stuff!
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'
export TERM=xterm-color
export CLICOLOR="true"
export LSCOLORS="exfxcxdxbxegedabagacad"

### QT blargh
export QMAKESPEC="macx-g++"

### Build against MySQL libraries!
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/mysql/lib/

### Node
export NODE_PATH=/usr/local/lib/node

### Python 2.6.5 + Virtualenv!
export PATH=/usr/local/Cellar/python/2.7.3/bin:/usr/local/share/python:/usr/local/Cellar/python2.6/2.6.5/bin:$PATH
source /usr/local/Cellar/python2.6/2.6.5/bin/virtualenvwrapper.sh
export PYTHONPATH=:/usr/local/lib/python2.6/site-packages:$PYTHONPATH
export PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache/
export VIRTUALENV_DISTRIBUTE=true

### CUDA
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

### Android Development
export ANDROID_SDK=~/android/adt-bundle-mac-x86_64/sdk
export ANDROID_HOME=$ANDROID_SDK
export ANDROID_NDK=~/android/android-ndk-r9
export PATH=$ANDROID_NDK:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$PATH
alias kt='keytool -genkey -v  -keypass abc123 -storepass abc123 -keystore example.keystore -alias example-alias -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=company name, OU=org unit 1, O=org 1, L=Austin, S=TX, C=US"'

### C/C++
export CMAKE_C_COMPILER_ENV_VAR=CC
export CMAKE_CXX_COMPILER_ENV_VAR=CXX

#git bash autocomplete
. ./.git-completion.sh

#command prompt
PS1='[\D{+%g.%m.%d} \t \W$(__git_ps1 " (%s)")]\$ '

# workon home || mkvirtualenv home && workon home

# Github/Gist
export GITHUB_USER="braebot"
eval "$(hub alias -s)"

# Go
export GOROOT=/usr/local/Cellar/go/1.0.2
export PATH=$PATH:$GOROOT/bin
